name: node-desafio
on:
  pull_request:
    branches:
      - dev
jobs:
  ci-sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          node-version: 18.16.1
          vitest: 4.4.9
          vitest/coverage-v8": ^0.34.5
      - run: npx vitest --coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
